<?php
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Methods: GET, POST, OPTIONS");
header("Access-Control-Allow-Headers: Content-Type");

include 'database.php';

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(200);
    exit();
}

// Get report_id from query parameter
$report_id = isset($_GET['report_id']) ? intval($_GET['report_id']) : 0;

if (!$report_id) {
    header("HTTP/1.1 400 Bad Request");
    echo "No report_id provided.";
    exit;
}

try {
    // Get detailed land report information
    $sql = "SELECT 
                lr.report_id,
                lr.land_id,
                lr.user_id,
                lr.report_date,
                lr.land_description,
                lr.crop_recomendation,
                lr.ph_value,
                lr.organic_matter,
                lr.nitrogen_level,
                lr.phosphorus_level,
                lr.potassium_level,
                lr.environmental_notes,
                lr.status,
                l.location,
                l.size,
                l.payment_status,
                u.first_name,
                u.last_name,
                u.email,
                u.phone
            FROM land_report lr
            JOIN land l ON lr.land_id = l.land_id
            JOIN user u ON lr.user_id = u.user_id
            WHERE lr.report_id = ?";
    
    $stmt = $conn->prepare($sql);
    $stmt->bind_param("i", $report_id);
    $stmt->execute();
    $result = $stmt->get_result();

    if ($result->num_rows === 0) {
        header("HTTP/1.1 404 Not Found");
        echo "Report not found.";
        exit;
    }

    $report = $result->fetch_assoc();
    
    // Simple text-based PDF-like format (plain text)
    header("Content-Type: text/plain");
    header("Content-Disposition: attachment; filename=\"land_report_" . $report_id . ".txt\"");
    header("Cache-Control: private, max-age=0, must-revalidate");
    header("Pragma: public");

    // Generate plain text report that can be saved as .txt
    echo generateTextReport($report);
    
} catch (Exception $e) {
    header("HTTP/1.1 500 Internal Server Error");
    echo "Failed to generate report: " . $e->getMessage();
}

function generateTextReport($report) {
    $text = "================================================================================\n";
    $text .= "                    FARM MASTER - LAND ASSESSMENT REPORT                       \n";
    $text .= "================================================================================\n\n";
    
    $text .= "Report ID: " . $report['report_id'] . "\n";
    $text .= "Generated: " . date('F j, Y', strtotime($report['report_date'])) . "\n\n";
    
    $text .= "LANDOWNER INFORMATION\n";
    $text .= "---------------------\n";
    $text .= "Name: " . $report['first_name'] . ' ' . $report['last_name'] . "\n";
    $text .= "Email: " . $report['email'] . "\n";
    $text .= "Phone: " . $report['phone'] . "\n\n";
    
    $text .= "LAND INFORMATION\n";
    $text .= "----------------\n";
    $text .= "Location: " . $report['location'] . "\n";
    $text .= "Size: " . $report['size'] . " acres\n";
    $text .= "Payment Status: " . $report['payment_status'] . "\n\n";
    
    $text .= "SOIL ANALYSIS RESULTS\n";
    $text .= "---------------------\n";
    $text .= "pH Value: " . ($report['ph_value'] ? number_format($report['ph_value'], 1) : 'Not tested') . "\n";
    $text .= "Organic Matter: " . ($report['organic_matter'] ? number_format($report['organic_matter'], 2) . '%' : 'Not tested') . "\n";
    $text .= "Nitrogen Level: " . ($report['nitrogen_level'] ?: 'Not tested') . "\n";
    $text .= "Phosphorus Level: " . ($report['phosphorus_level'] ?: 'Not tested') . "\n";
    $text .= "Potassium Level: " . ($report['potassium_level'] ?: 'Not tested') . "\n\n";
    
    if ($report['environmental_notes']) {
        $text .= "ENVIRONMENTAL ASSESSMENT\n";
        $text .= "------------------------\n";
        $text .= wordwrap($report['environmental_notes'], 78) . "\n\n";
    }
    
    $text .= "ASSESSMENT DETAILS\n";
    $text .= "------------------\n";
    $text .= "Report Status: " . $report['status'] . "\n";
    $text .= "Land Description:\n" . wordwrap($report['land_description'], 78) . "\n\n";
    
    $text .= "CROP RECOMMENDATIONS\n";
    $text .= "--------------------\n";
    $text .= wordwrap($report['crop_recomendation'], 78) . "\n\n";
    
    $text .= "================================================================================\n";
    $text .= "This report was generated by Farm Master Assessment System\n";
    $text .= "For questions about this report, please contact our support team\n";
    $text .= "================================================================================\n";
    
    return $text;
}

$conn->close();
?>
